ui: tape
browsers:
  - name: microsoftedge
    version: oldest..latest
  - name: chrome
    version: 39..latest
  - name: firefox
    version: 34..latest
  - name: safari
    version: 5..latest
  - name: ie
    version: 6..latest
  - name: opera
    version: 11..latest
  - name: iphone
    version: 5.1..latest
  - name: ipad
    version: 5.1..latest
  - name: android
    version: 4.0..latest